name: Deploy Flint Web
on:
  push:
    branches:
      - "main"

jobs:
  build-flint-web:
    environment: development
    env:
      FLAT_UA: ${{ secrets.FLAT_UA }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: |
          node ./scripts/ci/remove-workspace-packages.js web
          node ./scripts/ci/remove-package-scripts-hooks.js
          # failure automatically retries 3 times
          pnpm i || pnpm i || pnpm i

      - name: Build flint web development
        run: pnpm -F flint-web build -m development

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Reset dockerignore
        run: |
          echo "*" > .dockerignore
          echo "!web/flint-web/dist" >> .dockerignore
          echo "!web/flint-web/deploy/nginx" >> .dockerignore

      - name: Build and push images
        env:
          COMMIT_SHA_TAG: development-${{ github.sha }}
          LATEST_DEV_TAG: latest
        run: |
          docker build . -f web/flint-web/deploy/Dockerfile -t shunyue/flint-web:$COMMIT_SHA_TAG -t shunyue/flint-web:$LATEST_DEV_TAG
          docker push shunyue/flint-web:$COMMIT_SHA_TAG
          docker push shunyue/flint-web:$LATEST_DEV_TAG

  deploy-flint-web:
    runs-on: ubuntu-latest
    needs: build-flint-web
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.4
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: DOCKERHUB_USERNAME
          script: |
            docker pull $DOCKERHUB_USERNAME/flint-web:latest
            docker rm -f flint-web
            docker run -dit -p 3001:80 --name flint-web $DOCKERHUB_USERNAME/flint-web:latest
